name: academic_master
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  analyzer: ^5.10.0
  animations: ^2.0.7
  another_flushbar: ^1.12.29
  auto_route: ^6.0.5
  bloc: ^8.1.1
  bloc_test: ^9.1.1
  cached_network_image: ^3.2.3
  circular_reveal_animation: ^2.0.1
  cloud_firestore: ^4.5.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.2.7
  firebase_auth: ^4.4.0

  firebase_core: ^2.9.0

  firebase_storage: ^11.1.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_cached_pdfview: ^0.4.1
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.7.0
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_swipe_action_cell: ^3.1.0
  flutter_zoom_drawer: ^3.0.4+1
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  http: ^0.13.5
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  kt_dart: ^1.1.0
  line_icons: ^2.0.1
  loading_indicator: ^3.1.0
  lottie: ^2.3.2
  mockito: ^5.4.0
  modal_bottom_sheet: ^3.0.0-pre
  nil: ^1.1.1
  path_provider: ^2.0.14
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  razorpay_flutter: ^1.3.4
  responsive_framework: ^0.2.0
  rxdart: ^0.27.7
  selectable_autolink_text: ^2.5.0
  share: ^2.0.4
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  webview_flutter: ^4.0.7


dev_dependencies:
  auto_route_generator: ^6.0.3
  build_runner: ^2.3.3
  flutter_test:

    sdk: flutter
  freezed: ^2.3.2

  json_serializable: ^6.6.1
  lint: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottiefiles/
    - assets/icons/

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/circular.otf
    - family: Circular_Bold
      fonts:
        - asset: assets/fonts/CircularStdBold.otf
    - family: Circular_Medium
      fonts:
        - asset: assets/fonts/CircularStdMedium.otf
